<?php

/*
* Title                   : Wall/Grid Gallery (WordPress Plugin)
* Version                 : 1.8
* File                    : templates.php
* File Version            : 1.7
* Created / Last Modified : 25 March 2013
* Author                  : Dot on Paper
* Copyright               : © 2011 Dot on Paper
* Website                 : http://www.dotonpaper.net
* Description             : Wall/Grid Gallery Templates Class.
*/

    if (!class_exists("DOPWGGTemplates")){
        class DOPWGGTemplates{
            function DOPWGGTemplates(){// Constructor.
            }

            function galleriesList(){// Return Template    
                global $blog_id;
?>
    <script type="text/JavaScript">
        var DOPWGG_curr_page = "Galleries List",
        DOPWGG_plugin_url = "<?php echo WP_PLUGIN_URL.'/dopwgg/'?>",
        DOPWGG_plugin_abs = "<?php echo ABSPATH.'wp-content/plugins/dopwgg/'?>",

        DOPWGG_TITLE = "<?php echo DOPWGG_TITLE?>",

        // Loading ...
        DOPWGG_LOAD = "<?php echo DOPWGG_LOAD?>",
        DOPWGG_GALLERIES_LOADED = "<?php echo DOPWGG_GALLERIES_LOADED?>",
        DOPWGG_IMAGES_LOADED = "<?php echo DOPWGG_IMAGES_LOADED?>",
        DOPWGG_NO_GALLERIES = "<?php echo DOPWGG_NO_GALLERIES?>",
        DOPWGG_NO_IMAGES = "<?php echo DOPWGG_NO_IMAGES?>",
        DOPWGG_GALLERY_LOADED = "<?php echo DOPWGG_GALLERY_LOADED?>",
        DOPWGG_IMAGE_LOADED = "<?php echo DOPWGG_IMAGE_LOADED?>",

        // Save ...
        DOPWGG_SAVE = "<?php echo DOPWGG_SAVE?>",
        DOPWGG_SELECT_FILE = "<?php echo DOPWGG_SELECT_FILE?>",

        // Help
        DOPWGG_GALLERIES_HELP = "<?php echo DOPWGG_GALLERIES_HELP?>",
        DOPWGG_GALLERIES_EDIT_INFO_HELP = "<?php echo DOPWGG_GALLERIES_EDIT_INFO_HELP?>",
        DOPWGG_GALLERY_EDIT_HELP = "<?php echo DOPWGG_GALLERY_EDIT_HELP?>",
        DOPWGG_GALLERY_EDIT_INFO_HELP = "<?php echo DOPWGG_GALLERY_EDIT_INFO_HELP?>",
        DOPWGG_ADD_IMAGES_HELP = "<?php echo DOPWGG_ADD_IMAGES_HELP?>",
        DOPWGG_ADD_IMAGES_HELP_WP = "<?php echo DOPWGG_ADD_IMAGES_HELP_WP?>",
        DOPWGG_ADD_IMAGES_HELP_AJAX = "<?php echo DOPWGG_ADD_IMAGES_HELP_AJAX?>",
        DOPWGG_ADD_IMAGES_HELP_UPLOADIFY = "<?php echo DOPWGG_ADD_IMAGES_HELP_UPLOADIFY?>",
        DOPWGG_ADD_IMAGES_HELP_FTP = "<?php echo DOPWGG_ADD_IMAGES_HELP_FTP?>",
        DOPWGG_IMAGE_EDIT_HELP = "<?php echo DOPWGG_IMAGE_EDIT_HELP?>",

        // Form
        DOPWGG_SUBMIT = "<?php echo DOPWGG_SUBMIT?>",
        DOPWGG_DELETE = "<?php echo DOPWGG_DELETE?>",
        DOPWGG_DEFAULT = "<?php echo DOPWGG_DEFAULT?>",

        // Add Gallery
        DOPWGG_ADD_GALLERY_NAME = "<?php echo DOPWGG_ADD_GALLERY_NAME?>",
        DOPWGG_ADD_GALLERY_SUBMIT = "<?php echo DOPWGG_ADD_GALLERY_SUBMIT?>",
        DOPWGG_ADD_GALLERY_SUBMITED = "<?php echo DOPWGG_ADD_GALLERY_SUBMITED?>",
        DOPWGG_ADD_GALERRY_SUCCESS = "<?php echo DOPWGG_ADD_GALERRY_SUCCESS?>",

        // Edit Galleries
        DOPWGG_EDIT_GALLERIES_SUBMIT = "<?php echo DOPWGG_EDIT_GALLERIES_SUBMIT?>",
        DOPWGG_EDIT_GALLERIES_SUCCESS = "<?php echo DOPWGG_EDIT_GALLERIES_SUCCESS?>",

        // Edit Gallery
        DOPWGG_EDIT_GALLERY_SUBMIT = "<?php echo DOPWGG_EDIT_GALLERY_SUBMIT?>",
        DOPWGG_EDIT_GALLERY_SUCCESS = "<?php echo DOPWGG_EDIT_GALLERY_SUCCESS?>",
        DOPWGG_EDIT_GALLERY_USE_DEFAULT_CONFIRMATION = "<?php echo DOPWGG_EDIT_GALLERY_USE_DEFAULT_CONFIRMATION?>",

        // Delete Gallery
        DOPWGG_DELETE_GALLERY_CONFIRMATION = "<?php echo DOPWGG_DELETE_GALLERY_CONFIRMATION?>",
        DOPWGG_DELETE_GALLERY_SUBMIT = "<?php echo DOPWGG_DELETE_GALLERY_SUBMIT?>",
        DOPWGG_DELETE_GALLERY_SUBMITED = "<?php echo DOPWGG_DELETE_GALLERY_SUBMITED?>",
        DOPWGG_DELETE_GALERRY_SUCCESS = "<?php echo DOPWGG_DELETE_GALERRY_SUCCESS?>",

        // Add Image
        DOPWGG_ADD_IMAGE_SUBMIT = "<?php echo DOPWGG_ADD_IMAGE_SUBMIT?>",
        DOPWGG_ADD_IMAGE_WP_UPLOAD = "<?php echo DOPWGG_ADD_IMAGE_WP_UPLOAD?>",
        DOPWGG_ADD_IMAGE_SIMPLE_UPLOAD = "<?php echo DOPWGG_ADD_IMAGE_SIMPLE_UPLOAD?>",
        DOPWGG_ADD_IMAGE_MULTIPLE_UPLOAD = "<?php echo DOPWGG_ADD_IMAGE_MULTIPLE_UPLOAD?>",
        DOPWGG_ADD_IMAGE_FTP_UPLOAD = "<?php echo DOPWGG_ADD_IMAGE_FTP_UPLOAD?>",
        DOPWGG_ADD_IMAGE_SUBMITED = "<?php echo DOPWGG_ADD_IMAGE_SUBMITED?>",
        DOPWGG_ADD_IMAGE_SUCCESS = "<?php echo DOPWGG_ADD_IMAGE_SUCCESS?>",
        DOPWGG_SELECT_IMAGES = "<?php echo DOPWGG_SELECT_IMAGES?>",
        DOPWGG_SELECT_FTP_IMAGES = "<?php echo DOPWGG_SELECT_FTP_IMAGES?>",

        // Sort Image
        DOPWGG_SORT_IMAGES_SUBMITED = "<?php echo DOPWGG_SORT_IMAGES_SUBMITED?>",
        DOPWGG_SORT_IMAGES_SUCCESS = "<?php echo DOPWGG_SORT_IMAGES_SUCCESS?>",

        // Edit Image
        DOPWGG_EDIT_IMAGE_SUBMIT = "<?php echo DOPWGG_EDIT_IMAGE_SUBMIT?>",
        DOPWGG_EDIT_IMAGE_SUCCESS = "<?php echo DOPWGG_EDIT_IMAGE_SUCCESS?>",
        DOPWGG_EDIT_IMAGE_CROP_THUMBNAIL = "<?php echo DOPWGG_EDIT_IMAGE_CROP_THUMBNAIL?>",
        DOPWGG_EDIT_IMAGE_CURRENT_THUMBNAIL = "<?php echo DOPWGG_EDIT_IMAGE_CURRENT_THUMBNAIL?>",
        DOPWGG_EDIT_IMAGE_TITLE = "<?php echo DOPWGG_EDIT_IMAGE_TITLE?>",
        DOPWGG_EDIT_IMAGE_CAPTION = "<?php echo DOPWGG_EDIT_IMAGE_CAPTION?>",
        DOPWGG_EDIT_IMAGE_MEDIA = "<?php echo DOPWGG_EDIT_IMAGE_MEDIA?>",
        DOPWGG_EDIT_IMAGE_LINK = "<?php echo DOPWGG_EDIT_IMAGE_LINK?>",
        DOPWGG_EDIT_IMAGE_LINK_TARGET = "<?php echo DOPWGG_EDIT_IMAGE_LINK_TARGET?>",
        DOPWGG_EDIT_IMAGE_ENABLED = "<?php echo DOPWGG_EDIT_IMAGE_ENABLED?>",

        // Delete Image
        DOPWGG_DELETE_IMAGE_CONFIRMATION = "<?php echo DOPWGG_DELETE_IMAGE_CONFIRMATION?>",
        DOPWGG_DELETE_IMAGE_SUBMIT = "<?php echo DOPWGG_DELETE_IMAGE_SUBMIT?>",
        DOPWGG_DELETE_IMAGE_SUBMITED = "<?php echo DOPWGG_DELETE_IMAGE_SUBMITED?>",
        DOPWGG_DELETE_IMAGE_SUCCESS = "<?php echo DOPWGG_DELETE_IMAGE_SUCCESS?>",

        // TinyMCE
        DOPWGG_TINYMCE_ADD = "<?php echo DOPWGG_TINYMCE_ADD?>";

        // Settings
        DOPWGG_DEFAULT_SETTINGS = "<?php echo DOPWGG_DEFAULT_SETTINGS?>",
        
        DOPWGG_GENERAL_STYLES_SETTINGS = "<?php echo DOPWGG_GENERAL_STYLES_SETTINGS?>",
        DOPWGG_GALLERY_NAME = "<?php echo DOPWGG_GALLERY_NAME?>",
        DOPWGG_DATA_PARSE_METHOD = "<?php echo DOPWGG_DATA_PARSE_METHOD?>",
        DOPWGG_WIDTH = "<?php echo DOPWGG_WIDTH?>",
        DOPWGG_HEIGHT = "<?php echo DOPWGG_HEIGHT?>",
        DOPWGG_BG_COLOR = "<?php echo DOPWGG_BG_COLOR?>",
        DOPWGG_BG_ALPHA = "<?php echo DOPWGG_BG_ALPHA?>",
        DOPWGG_NO_LINES = "<?php echo DOPWGG_NO_LINES?>",
        DOPWGG_NO_COLUMNS = "<?php echo DOPWGG_NO_COLUMNS?>",
        DOPWGG_IMAGES_ORDER = "<?php echo DOPWGG_IMAGES_ORDER?>",
        DOPWGG_RESPONSIVE_ENABLED = "<?php echo DOPWGG_RESPONSIVE_ENABLED?>",
        
        DOPWGG_THUMBNAILS_STYLES_SETTINGS = "<?php echo DOPWGG_THUMBNAILS_STYLES_SETTINGS?>",
        DOPWGG_THUMBNAILS_SPACING = "<?php echo DOPWGG_THUMBNAILS_SPACING?>",
        DOPWGG_THUMBNAILS_PADDING_TOP = "<?php echo DOPWGG_THUMBNAILS_PADDING_TOP?>",
        DOPWGG_THUMBNAILS_PADDING_RIGHT = "<?php echo DOPWGG_THUMBNAILS_PADDING_RIGHT?>",
        DOPWGG_THUMBNAILS_PADDING_BOTTOM = "<?php echo DOPWGG_THUMBNAILS_PADDING_BOTTOM?>",
        DOPWGG_THUMBNAILS_PADDING_LEFT = "<?php echo DOPWGG_THUMBNAILS_PADDING_LEFT?>",
        DOPWGG_THUMBNAILS_NAVIGATION = "<?php echo DOPWGG_THUMBNAILS_NAVIGATION?>",
        DOPWGG_THUMBNAILS_SCROLL_SCRUB_COLOR = "<?php echo DOPWGG_THUMBNAILS_SCROLL_SCRUB_COLOR?>",
        DOPWGG_THUMBNAILS_SCROLL_BAR_COLOR = "<?php echo DOPWGG_THUMBNAILS_SCROLL_BAR_COLOR?>",
        DOPWGG_THUMBNAILS_INFO = "<?php echo DOPWGG_THUMBNAILS_INFO?>",

        DOPWGG_THUMBNAIL_STYLES_SETTINGS = "<?php echo DOPWGG_THUMBNAIL_STYLES_SETTINGS?>",
        DOPWGG_THUMBNAIL_LOADER = "<?php echo DOPWGG_THUMBNAIL_LOADER?>",
        DOPWGG_ADD_THUMBNAIL_LOADER_SUBMITED = "<?php echo DOPWGG_ADD_THUMBNAIL_LOADER_SUBMITED?>",
        DOPWGG_ADD_THUMBNAIL_LOADER_SUCCESS = "<?php echo DOPWGG_ADD_THUMBNAIL_LOADER_SUCCESS?>",
        DOPWGG_THUMBNAIL_WIDTH = "<?php echo DOPWGG_THUMBNAIL_WIDTH?>",
        DOPWGG_THUMBNAIL_HEIGHT = "<?php echo DOPWGG_THUMBNAIL_HEIGHT?>",
        DOPWGG_THUMBNAIL_WIDTH_MOBILE = "<?php echo DOPWGG_THUMBNAIL_WIDTH_MOBILE?>",
        DOPWGG_THUMBNAIL_HEIGHT_MOBILE = "<?php echo DOPWGG_THUMBNAIL_HEIGHT_MOBILE?>",
        DOPWGG_THUMBNAIL_ALPHA = "<?php echo DOPWGG_THUMBNAIL_ALPHA?>",
        DOPWGG_THUMBNAIL_ALPHA_HOVER = "<?php echo DOPWGG_THUMBNAIL_ALPHA_HOVER?>",
        DOPWGG_THUMBNAIL_BG_COLOR = "<?php echo DOPWGG_THUMBNAIL_BG_COLOR?>",
        DOPWGG_THUMBNAIL_BG_COLOR_HOVER = "<?php echo DOPWGG_THUMBNAIL_BG_COLOR_HOVER?>",
        DOPWGG_THUMBNAIL_BORDER_SIZE = "<?php echo DOPWGG_THUMBNAIL_BORDER_SIZE?>",
        DOPWGG_THUMBNAIL_BORDER_COLOR = "<?php echo DOPWGG_THUMBNAIL_BORDER_COLOR?>",
        DOPWGG_THUMBNAIL_BORDER_COLOR_HOVER = "<?php echo DOPWGG_THUMBNAIL_BORDER_COLOR_HOVER?>",
        DOPWGG_THUMBNAIL_PADDING_TOP = "<?php echo DOPWGG_THUMBNAIL_PADDING_TOP?>",
        DOPWGG_THUMBNAIL_PADDING_RIGHT = "<?php echo DOPWGG_THUMBNAIL_PADDING_RIGHT?>",
        DOPWGG_THUMBNAIL_PADDING_BOTTOM = "<?php echo DOPWGG_THUMBNAIL_PADDING_BOTTOM?>",
        DOPWGG_THUMBNAIL_PADDING_LEFT = "<?php echo DOPWGG_THUMBNAIL_PADDING_LEFT?>",

        DOPWGG_LIGHTBOX_STYLES_SETTINGS = "<?php echo DOPWGG_LIGHTBOX_STYLES_SETTINGS?>",
        DOPWGG_LIGHTBOX_POSITION = "<?php echo DOPWGG_LIGHTBOX_POSITION?>",
        DOPWGG_LIGHTBOX_WINDOW_COLOR = "<?php echo DOPWGG_LIGHTBOX_WINDOW_COLOR?>",
        DOPWGG_LIGHTBOX_WINDOW_ALPHA = "<?php echo DOPWGG_LIGHTBOX_WINDOW_ALPHA?>",
        DOPWGG_LIGHTBOX_LOADER = "<?php echo DOPWGG_LIGHTBOX_LOADER?>",
        DOPWGG_ADD_LIGHTBOX_LOADER_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_LOADER_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_LOADER_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_LOADER_SUCCESS?>",
        DOPWGG_LIGHTBOX_BACKGROUND_COLOR = "<?php echo DOPWGG_LIGHTBOX_BACKGROUND_COLOR?>",
        DOPWGG_LIGHTBOX_BACKGROUND_ALPHA = "<?php echo DOPWGG_LIGHTBOX_BACKGROUND_ALPHA?>",
        DOPWGG_LIGHTBOX_MARGIN_TOP = "<?php echo DOPWGG_LIGHTBOX_MARGIN_TOP?>",
        DOPWGG_LIGHTBOX_MARGIN_RIGHT = "<?php echo DOPWGG_LIGHTBOX_MARGIN_RIGHT?>",
        DOPWGG_LIGHTBOX_MARGIN_BOTTOM = "<?php echo DOPWGG_LIGHTBOX_MARGIN_BOTTOM?>",
        DOPWGG_LIGHTBOX_MARGIN_LEFT = "<?php echo DOPWGG_LIGHTBOX_MARGIN_LEFT?>",
        DOPWGG_LIGHTBOX_PADDING_TOP = "<?php echo DOPWGG_LIGHTBOX_PADDING_TOP?>",
        DOPWGG_LIGHTBOX_PADDING_RIGHT = "<?php echo DOPWGG_LIGHTBOX_PADDING_RIGHT?>",
        DOPWGG_LIGHTBOX_PADDING_BOTTOM = "<?php echo DOPWGG_LIGHTBOX_PADDING_BOTTOM?>",
        DOPWGG_LIGHTBOX_PADDING_LEFT = "<?php echo DOPWGG_LIGHTBOX_PADDING_LEFT?>",
    
        DOPWGG_LIGHTBOX_NAVIGATION_STYLES_SETTINGS = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_STYLES_SETTINGS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_PREV = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_PREV?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER?>",        
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_PREV_HOVER_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_NEXT = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_NEXT?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_NEXT_HOVER = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_NEXT_HOVER?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_HOVER_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_HOVER_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_HOVER_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_NEXT_HOVER_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_CLOSE = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_CLOSE?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_SUCCESS?>",
        DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_HOVER = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_HOVER?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_HOVER_SUBMITED = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_HOVER_SUBMITED?>",
        DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_HOVER_SUCCESS = "<?php echo DOPWGG_ADD_LIGHTBOX_NAVIGATION_CLOSE_HOVER_SUCCESS?>",
    
        DOPWGG_CAPTION_STYLES_SETTINGS = "<?php echo DOPWGG_CAPTION_STYLES_SETTINGS?>",
        DOPWGG_CAPTION_HEIGHT = "<?php echo DOPWGG_CAPTION_HEIGHT?>",
        DOPWGG_CAPTION_TITLE_COLOR = "<?php echo DOPWGG_CAPTION_TITLE_COLOR?>",
        DOPWGG_CAPTION_TEXT_COLOR = "<?php echo DOPWGG_CAPTION_TEXT_COLOR?>",
        DOPWGG_CAPTION_SCROLL_SCRUB_COLOR = "<?php echo DOPWGG_CAPTION_SCROLL_SCRUB_COLOR?>",
        DOPWGG_CAPTION_SCROLL_BG_COLOR = "<?php echo DOPWGG_CAPTION_SCROLL_BG_COLOR?>",

        DOPWGG_SOCIAL_SHARE_STYLES_SETTINGS = "<?php echo DOPWGG_SOCIAL_SHARE_STYLES_SETTINGS?>",
        DOPWGG_SOCIAL_SHARE_ENABLED = "<?php echo DOPWGG_SOCIAL_SHARE_ENABLED?>",
        DOPWGG_SOCIAL_SHARE_LIGHTBOX = "<?php echo DOPWGG_SOCIAL_SHARE_LIGHTBOX?>",
        DOPWGG_SOCIAL_SHARE_LIGHTBOX_SUBMITED = "<?php echo DOPWGG_SOCIAL_SHARE_LIGHTBOX_SUBMITED?>",
        DOPWGG_SOCIAL_SHARE_LIGHTBOX_SUCCESS = "<?php echo DOPWGG_SOCIAL_SHARE_LIGHTBOX_SUCCESS?>",

        DOPWGG_TOOLTIP_STYLES_SETTINGS = "<?php echo DOPWGG_TOOLTIP_STYLES_SETTINGS?>",
        DOPWGG_TOOLTIP_BG_COLOR = "<?php echo DOPWGG_TOOLTIP_BG_COLOR?>",
        DOPWGG_TOOLTIP_STROKE_COLOR = "<?php echo DOPWGG_TOOLTIP_STROKE_COLOR?>",
        DOPWGG_TOOLTIP_TEXT_COLOR = "<?php echo DOPWGG_TOOLTIP_TEXT_COLOR?>",
    
        DOPWGG_LABEL_STYLES_SETTINGS = "<?php echo DOPWGG_LABEL_STYLES_SETTINGS?>",    
        DOPWGG_LABEL_POSITION = "<?php echo DOPWGG_LABEL_POSITION?>",
        DOPWGG_LABEL_TEXT_COLOR = "<?php echo DOPWGG_LABEL_TEXT_COLOR?>",
        DOPWGG_LABEL_TEXT_COLOR_HOVER = "<?php echo DOPWGG_LABEL_TEXT_COLOR_HOVER?>",

        DOPWGG_GO_TOP = "<?php echo DOPWGG_GO_TOP?>",
        
        DOPWGG_GALLERY_NAME_INFO = "<?php echo DOPWGG_GALLERY_NAME_INFO?>",
        DOPWGG_DATA_PARSE_METHOD_INFO = "<?php echo DOPWGG_DATA_PARSE_METHOD_INFO?>",
        DOPWGG_WIDTH_INFO = "<?php echo DOPWGG_WIDTH_INFO?>",
        DOPWGG_HEIGHT_INFO = "<?php echo DOPWGG_HEIGHT_INFO?>",
        DOPWGG_BG_COLOR_INFO = "<?php echo DOPWGG_BG_COLOR_INFO?>",
        DOPWGG_BG_ALPHA_INFO = "<?php echo DOPWGG_BG_ALPHA_INFO?>",
        DOPWGG_NO_LINES_INFO = "<?php echo DOPWGG_NO_LINES_INFO?>",
        DOPWGG_NO_COLUMNS_INFO = "<?php echo DOPWGG_NO_COLUMNS_INFO?>",
        DOPWGG_IMAGES_ORDER_INFO = "<?php echo DOPWGG_IMAGES_ORDER_INFO?>",
        DOPWGG_RESPONSIVE_ENABLED_INFO = "<?php echo DOPWGG_RESPONSIVE_ENABLED_INFO?>",

        DOPWGG_THUMBNAILS_SPACING_INFO = "<?php echo DOPWGG_THUMBNAILS_SPACING_INFO?>",
        DOPWGG_THUMBNAILS_PADDING_TOP_INFO = "<?php echo DOPWGG_THUMBNAILS_PADDING_TOP_INFO?>",
        DOPWGG_THUMBNAILS_PADDING_RIGHT_INFO = "<?php echo DOPWGG_THUMBNAILS_PADDING_RIGHT_INFO?>",
        DOPWGG_THUMBNAILS_PADDING_BOTTOM_INFO = "<?php echo DOPWGG_THUMBNAILS_PADDING_BOTTOM_INFO?>",
        DOPWGG_THUMBNAILS_PADDING_LEFT_INFO = "<?php echo DOPWGG_THUMBNAILS_PADDING_LEFT_INFO?>",
        DOPWGG_THUMBNAILS_NAVIGATION_INFO = "<?php echo DOPWGG_THUMBNAILS_NAVIGATION_INFO?>",
        DOPWGG_THUMBNAILS_SCROLL_SCRUB_COLOR_INFO = "<?php echo DOPWGG_THUMBNAILS_SCROLL_SCRUB_COLOR_INFO?>",
        DOPWGG_THUMBNAILS_SCROLL_BAR_COLOR_INFO = "<?php echo DOPWGG_THUMBNAILS_SCROLL_BAR_COLOR_INFO?>",
        DOPWGG_THUMBNAILS_INFO_INFO = "<?php echo DOPWGG_THUMBNAILS_INFO_INFO?>",
    
        DOPWGG_THUMBNAIL_LOADER_INFO = "<?php echo DOPWGG_THUMBNAIL_LOADER_INFO?>",
        DOPWGG_THUMBNAIL_WIDTH_INFO = "<?php echo DOPWGG_THUMBNAIL_WIDTH_INFO?>",
        DOPWGG_THUMBNAIL_HEIGHT_INFO = "<?php echo DOPWGG_THUMBNAIL_HEIGHT_INFO?>",
        DOPWGG_THUMBNAIL_WIDTH_MOBILE_INFO = "<?php echo DOPWGG_THUMBNAIL_WIDTH_MOBILE_INFO?>",
        DOPWGG_THUMBNAIL_HEIGHT_MOBILE_INFO = "<?php echo DOPWGG_THUMBNAIL_HEIGHT_MOBILE_INFO?>",
        DOPWGG_THUMBNAIL_ALPHA_INFO = "<?php echo DOPWGG_THUMBNAIL_ALPHA_INFO?>",
        DOPWGG_THUMBNAIL_ALPHA_HOVER_INFO = "<?php echo DOPWGG_THUMBNAIL_ALPHA_HOVER_INFO?>",
        DOPWGG_THUMBNAIL_BG_COLOR_INFO = "<?php echo DOPWGG_THUMBNAIL_BG_COLOR_INFO?>",
        DOPWGG_THUMBNAIL_BG_COLOR_HOVER_INFO = "<?php echo DOPWGG_THUMBNAIL_BG_COLOR_HOVER_INFO?>",
        DOPWGG_THUMBNAIL_BORDER_SIZE_INFO = "<?php echo DOPWGG_THUMBNAIL_BORDER_SIZE_INFO?>",
        DOPWGG_THUMBNAIL_BORDER_COLOR_INFO = "<?php echo DOPWGG_THUMBNAIL_BORDER_COLOR_INFO?>",
        DOPWGG_THUMBNAIL_BORDER_COLOR_HOVER_INFO = "<?php echo DOPWGG_THUMBNAIL_BORDER_COLOR_HOVER_INFO?>",
        DOPWGG_THUMBNAIL_PADDING_TOP_INFO = "<?php echo DOPWGG_THUMBNAIL_PADDING_TOP_INFO?>",
        DOPWGG_THUMBNAIL_PADDING_RIGHT_INFO = "<?php echo DOPWGG_THUMBNAIL_PADDING_RIGHT_INFO?>",
        DOPWGG_THUMBNAIL_PADDING_BOTTOM_INFO = "<?php echo DOPWGG_THUMBNAIL_PADDING_BOTTOM_INFO?>",
        DOPWGG_THUMBNAIL_PADDING_LEFT_INFO = "<?php echo DOPWGG_THUMBNAIL_PADDING_LEFT_INFO?>",

        DOPWGG_LIGHTBOX_POSITION_INFO = "<?php echo DOPWGG_LIGHTBOX_POSITION_INFO?>",
        DOPWGG_LIGHTBOX_WINDOW_COLOR_INFO = "<?php echo DOPWGG_LIGHTBOX_WINDOW_COLOR_INFO?>",
        DOPWGG_LIGHTBOX_WINDOW_ALPHA_INFO = "<?php echo DOPWGG_LIGHTBOX_WINDOW_ALPHA_INFO?>",
        DOPWGG_LIGHTBOX_LOADER_INFO = "<?php echo DOPWGG_LIGHTBOX_LOADER_INFO?>",
        DOPWGG_LIGHTBOX_BACKGROUND_COLOR_INFO = "<?php echo DOPWGG_LIGHTBOX_BACKGROUND_COLOR_INFO?>",
        DOPWGG_LIGHTBOX_BACKGROUND_ALPHA_INFO = "<?php echo DOPWGG_LIGHTBOX_BACKGROUND_ALPHA_INFO?>",
        DOPWGG_LIGHTBOX_MARGIN_TOP_INFO = "<?php echo DOPWGG_LIGHTBOX_MARGIN_TOP_INFO?>",
        DOPWGG_LIGHTBOX_MARGIN_RIGHT_INFO = "<?php echo DOPWGG_LIGHTBOX_MARGIN_RIGHT_INFO?>",
        DOPWGG_LIGHTBOX_MARGIN_BOTTOM_INFO = "<?php echo DOPWGG_LIGHTBOX_MARGIN_BOTTOM_INFO?>",
        DOPWGG_LIGHTBOX_MARGIN_LEFT_INFO = "<?php echo DOPWGG_LIGHTBOX_MARGIN_LEFT_INFO?>",
        DOPWGG_LIGHTBOX_PADDING_TOP_INFO = "<?php echo DOPWGG_LIGHTBOX_PADDING_TOP_INFO?>",
        DOPWGG_LIGHTBOX_PADDING_RIGHT_INFO = "<?php echo DOPWGG_LIGHTBOX_PADDING_RIGHT_INFO?>",
        DOPWGG_LIGHTBOX_PADDING_BOTTOM_INFO = "<?php echo DOPWGG_LIGHTBOX_PADDING_BOTTOM_INFO?>",
        DOPWGG_LIGHTBOX_PADDING_LEFT_INFO = "<?php echo DOPWGG_LIGHTBOX_PADDING_LEFT_INFO?>",
    
        DOPWGG_LIGHTBOX_NAVIGATION_PREV_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_PREV_INFO?>",
        DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_PREV_HOVER_INFO?>",
        DOPWGG_LIGHTBOX_NAVIGATION_NEXT_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_NEXT_INFO?>",
        DOPWGG_LIGHTBOX_NAVIGATION_NEXT_HOVER_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_NEXT_HOVER_INFO?>",
        DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_INFO?>",
        DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_HOVER_INFO = "<?php echo DOPWGG_LIGHTBOX_NAVIGATION_CLOSE_HOVER_INFO?>",
    
        DOPWGG_CAPTION_HEIGHT_INFO = "<?php echo DOPWGG_CAPTION_HEIGHT_INFO?>",
        DOPWGG_CAPTION_TITLE_COLOR_INFO = "<?php echo DOPWGG_CAPTION_TITLE_COLOR_INFO?>",
        DOPWGG_CAPTION_TEXT_COLOR_INFO = "<?php echo DOPWGG_CAPTION_TEXT_COLOR_INFO?>",
        DOPWGG_CAPTION_SCROLL_SCRUB_COLOR_INFO = "<?php echo DOPWGG_CAPTION_SCROLL_SCRUB_COLOR_INFO?>",
        DOPWGG_CAPTION_SCROLL_BG_COLOR_INFO = "<?php echo DOPWGG_CAPTION_SCROLL_BG_COLOR_INFO?>",
        
        DOPWGG_SOCIAL_SHARE_ENABLED_INFO = "<?php echo DOPWGG_SOCIAL_SHARE_ENABLED_INFO?>",
        DOPWGG_SOCIAL_SHARE_LIGHTBOX_INFO = "<?php echo DOPWGG_SOCIAL_SHARE_LIGHTBOX_INFO?>", 

        DOPWGG_TOOLTIP_BG_COLOR_INFO = "<?php echo DOPWGG_TOOLTIP_BG_COLOR_INFO?>",
        DOPWGG_TOOLTIP_STROKE_COLOR_INFO = "<?php echo DOPWGG_TOOLTIP_STROKE_COLOR_INFO?>",
        DOPWGG_TOOLTIP_TEXT_COLOR_INFO = "<?php echo DOPWGG_TOOLTIP_TEXT_COLOR_INFO?>",

        DOPWGG_LABEL_POSITION_INFO = "<?php echo DOPWGG_LABEL_POSITION_INFO?>",
        DOPWGG_LABEL_TEXT_COLOR_INFO = "<?php echo DOPWGG_LABEL_TEXT_COLOR_INFO?>";
        DOPWGG_LABEL_TEXT_COLOR_HOVER_INFO = "<?php echo DOPWGG_LABEL_TEXT_COLOR_HOVER_INFO?>";
    </script>
    <div class="wrap DOPWGG-admin">
        <h2><?php echo DOPWGG_TITLE?></h2>
        <div id="DOPWGG-admin-message"></div>
        <a href="http://envato-help.dotonpaper.net/wall-grid-gallery-wordpress-plugin.html#faq" target="_blank" class="DOPWGG-help"><?php echo DOPWGG_HELP_FAQ ?></a>
        <a href="http://envato-help.dotonpaper.net/wall-grid-gallery-wordpress-plugin.html" target="_blank" class="DOPWGG-help"><?php echo DOPWGG_HELP_DOCUMENTATION ?></a>
        
        <input type="hidden" id="blog_id" value="<?php echo $blog_id; ?>" />
        <input type="hidden" id="gallery_id" value="" />
        <br class="DOPWGG-clear" />
        <div class="main">
            <div class="column column1">
                <div class="column-header">
                    <div class="add-button">
                        <a href="javascript:dopwggAddGallery()" title="<?php echo DOPWGG_ADD_GALLERY_SUBMIT?>"></a>
                    </div>
                    <div class="edit-button">
                        <a href="javascript:dopwggShowDefaultSettings()" title="<?php echo DOPWGG_EDIT_GALLERIES_SUBMIT?>"></a>
                    </div>
                    <a href="javascript:void()" class="header-help" title="<?php echo DOPWGG_GALLERIES_HELP?>"></a>
                </div>
                <div class="column-content-container">
                    <div class="column-content">
                        &nbsp;
                    </div>
                </div>
            </div>
            <div class="column-separator"></div>
            <div class="column column2">
                <div class="column-header"></div>
                <div class="column-content-container">
                    <div class="column-content">
                        &nbsp;
                    </div>
                </div>
            </div>
            <div class="column-separator"></div>
            <div class="column column3">
                <div class="column-header"></div>
                <div class="column-content-container">
                    <div class="column-content">
                        &nbsp;
                    </div>
                </div>
            </div>
        </div>
        <br class="DOPWGG-clear" />
    </div>
<?php
            }
        }
    }
?>